ALTER TABLE `scores` MODIFY `grade_letter` VARCHAR(4) NOT NULL DEFAULT 'D',
    MODIFY `modifiers` INT UNSIGNED,
    MODIFY `clear_status` TINYINT(2) UNSIGNED NOT NULL DEFAULT '1',
    MODIFY `criticals` INT UNSIGNED NOT NULL DEFAULT '0',
    MODIFY `nears` INT UNSIGNED NOT NULL DEFAULT '0',
    MODIFY `errors` INT UNSIGNED NOT NULL DEFAULT '0',
    MODIFY `performance_rating` FLOAT UNSIGNED NOT NULL DEFAULT '0';
